### ISSUE TITLE
uninitialized constant Rack::UserLocale during rails 7 bootup

### ISSUE THREAD

**Issue by whysthatso** [technicalpanda/rack-user-locale#220]
hey
i'm trying to get this running in a rails 7 app.

got the gem installed, and listed:
```
Gem::Specification.all_names
=>  "rack-user-locale-2.0.1"
```

got the config entry in the application.rb:
```
module MyApp
  class Application < Rails::Application
    config.middleware.use Rack::UserLocale
  end
end
```

but upon server start in dev i get:

```
`<class:Application>': uninitialized constant Rack::UserLocale (NameError)
```

what am i doing wrong?

**Comment by schinery** [comment]
Hey @whysthatso, you either need to add `require "user_locale"` to your `application.rb` file or use this in your `Gemfile`:

```ruby
gem "rack-user-locale", require: "user_locale"
```

I can't remember why it is `user_locale` and not `rack_user_locale` as this was made awhile back, but adding either will allow you to start your Rails server.

Will update the README when I get a mo too.

**Comment by whysthatso** [comment]
yep, that did it.
